version: "3.8"

volumes:
  mongo-data:

services:
  app:
    build:
      context: .
      target: development
      args:
        APP_PATH: /home/node/app
    env_file: .env.example
    stdin_open: true
    tty: true
    volumes:
      - ./:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3000:3000
      - 9229
    depends_on:
      - mongo-db
  
  mongo-db:
    hostname: mongo
    image: mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongo admin --quiet | grep 1
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 10s
